# source: https://github.com/microsoft/RichCodeNavIndexer/blob/master/.github/workflows/dependency_updates.yml

name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: yarn up '!(yakshaving)'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          commit-message: Update all dependencies
          branch: automatic_dependency_updates
          title: Update all dependencies
          body: An updated update of all NPM dependencies.
          token: ${{ steps.generate-token.outputs.token }}
          labels: dependencies
          #reviewers: # optional
