name: Prettier

on:
  push:
    branches:
      - rewrite
  workflow_dispatch:

jobs:
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --check-cache

      - run: yarn run format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto format by prettier
