name: Tests

on:
  push:
    branches:
      - rewrite
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - rewrite
    paths-ignore:
      - '**.md'

jobs:
  test-coverage:
    name: Run Tests and Gather Coverage Reports

    if: github.event.push || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Installing Dependencies
        run: yarn install

      - name: Running Tests and Collecting Coverages
        run: yarn run collect-coverage

      - name: Posting Coverages
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
