name: Yakshaving NPM Publish

on:
  workflow_dispatch:
  push:
    branches:
      - rewrite
    paths:
      - 'packages/webapp-yakshaving/source/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn workspaces focus yakshaving

      - run: yarn workspace yakshaving build

      - run: yarn workspace yakshaving npm publish --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
